# Generated by Django 4.2.11 on 2024-06-16 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дедлайн'),
            preserve_default=False,
        ),
    ]
